# Generated by Django 4.2 on 2026-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dialog_alter_telegramuser_avatar_random_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
