# Generated by Django 4.2 on 2026-05-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='buy_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Где купить (ссылка)'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='item_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='api.telegramuser')),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
