# Generated by Django 4.2 on 2026-05-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ['-pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='dialog',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
