# Generated by Django 4.2 on 2026-05-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dialog_options_dialog_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Категория одежды',
                'verbose_name_plural': 'Категории одежды',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='clothing/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='clothing/thumbs/')),
                ('default_z_index', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.clothingcategory')),
            ],
            options={
                'verbose_name': 'Предмет одежды',
                'verbose_name_plural': 'Предметы одежды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('tag_type', models.CharField(choices=[('color', 'Цвет'), ('material', 'Материал'), ('style', 'Стиль'), ('season', 'Сезон'), ('brand', 'Бренд'), ('occasion', 'Повод')], max_length=20)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['tag_type', 'name'],
                'unique_together': {('slug', 'tag_type')},
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='outfits/previews/')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='outfits', to='api.clothingtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='api.telegramuser')),
            ],
            options={
                'verbose_name': 'Образ',
                'verbose_name_plural': 'Образы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_views', to='api.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_outfits', to='api.telegramuser')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_data', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clothingitem')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.outfit')),
            ],
            options={
                'verbose_name': 'Предмет в образе',
                'verbose_name_plural': 'Предметы в образе',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OutfitComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.outfit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.outfitcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_comments', to='api.telegramuser')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfits', models.ManyToManyField(blank=True, related_name='collections', to='api.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='api.telegramuser')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='api.clothingtag'),
        ),
        migrations.CreateModel(
            name='OutfitLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_likes', to='api.telegramuser')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'unique_together': {('outfit', 'user')},
            },
        ),
    ]
