# Generated by Django 4.2 on 2026-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_like_clothing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingcategory',
            name='icon_svg',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/', verbose_name='SVG иконка'),
        ),
        migrations.AlterField(
            model_name='clothingcategory',
            name='icon_class',
            field=models.CharField(blank=True, default='ri-shirt-line', max_length=50),
        ),
    ]
