# Generated by Django 4.2 on 2026-05-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clothingcategory_clothingitem_clothingtag_outfit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_rate', models.FloatField(default=0)),
                ('avg_view_duration', models.FloatField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('top_viewer_age_group', models.CharField(blank=True, max_length=20)),
                ('top_viewer_country', models.CharField(blank=True, max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.outfit')),
            ],
        ),
    ]
