# Generated by Django 4.2 on 2026-05-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_icon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingcategory',
            name='name',
            field=models.CharField(choices=[('top', 'Верхняя одежда'), ('shirt', 'Рубашки и футболки'), ('pants', 'Брюки'), ('dress', 'Платья'), ('skirt', 'Юбки'), ('shoes', 'Обувь'), ('accessories', 'Аксессуары'), ('hat', 'Головные уборы')], max_length=50, unique=True),
        ),
    ]
