# Generated by Django 4.2 on 2026-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clothingcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mannequin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='mannequins/')),
            ],
            options={
                'ordering': ['gender'],
            },
        ),
    ]
