# Generated by Django 5.2.7 on 2026-09-27 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_clothingitem_image_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingcategory",
            name="default_layer",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="clothingcategory",
            name="zone",
            field=models.CharField(
                choices=[
                    ("head", "Голова"),
                    ("upper", "Верх"),
                    ("lower", "Низ"),
                    ("full", "Всё тело"),
                    ("feet", "Стопы"),
                    ("accessory", "Аксессуар"),
                ],
                default="upper",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studio_items",
                to="api.telegramuser",
            ),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="fit_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="fitted_female",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="clothing/fitted/"
            ),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="fitted_male",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="clothing/fitted/"
            ),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="keypoints",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="season",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "Всесезон"),
                    ("summer", "Лето"),
                    ("demi", "Демисезон"),
                    ("winter", "Зима"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mannequin",
            name="anchors",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="mannequin",
            name="canvas",
            field=models.ImageField(
                blank=True, null=True, upload_to="mannequins/canvas/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shares",
                to="api.outfitpost",
            ),
        ),
        migrations.AddField(
            model_name="outfitpost",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="outfitpost",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outfitpost",
            name="remix_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remixes",
                to="api.outfitpost",
            ),
        ),
        migrations.AddField(
            model_name="outfitpost",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("all", "Все"),
                    ("followers", "Подписчики"),
                    ("private", "Только я"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="postclothingitem",
            name="fitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postclothingitem",
            name="flipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postclothingitem",
            name="normalized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="api.postcomment",
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("moderator", "Модератор"),
                    ("admin", "Администратор"),
                ],
                default="user",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("like", "Лайк"),
                    ("comment", "Комментарий"),
                    ("reply", "Ответ"),
                    ("follow", "Подписка"),
                    ("remix", "Ремикс"),
                    ("studio", "Студия"),
                ],
                max_length=20,
            ),
        ),
    ]
