# Generated by Django 5.2.7 on 2026-09-28 01:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_dialog_per_user_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfitpost",
            name="final_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.outfit_image_path
            ),
        ),
    ]
