services:
  db:
    image: postgres:18
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    command: >
      sh -c "./scripts/wait-for-it.sh db:5432 &&
            python manage.py migrate &&
            exec python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: