# Generated by Django 5.2.7 on 2026-09-28 00:58

import mobile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_backfill_mobile_fields"),
        ("mobile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginnonce",
            name="code",
            field=models.CharField(default=mobile.models._new_code, max_length=4),
        ),
        migrations.AddField(
            model_name="loginnonce",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginnonce",
            name="device",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="rotated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="loginnonce",
            index=models.Index(
                fields=["created_at"], name="mobile_logi_created_ba64b2_idx"
            ),
        ),
    ]
