# Generated by Django 5.2.7 on 2026-09-27 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0009_clothingcategory_default_layer_clothingcategory_zone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarmentJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Мужское"),
                            ("female", "Женское"),
                            ("unisex", "Унисекс"),
                        ],
                        default="unisex",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.ImageField(max_length=500, upload_to="studio/source/"),
                ),
                (
                    "cutout",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="studio/cutout/",
                    ),
                ),
                (
                    "fitted_male",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="studio/fitted/",
                    ),
                ),
                (
                    "fitted_female",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="studio/fitted/",
                    ),
                ),
                (
                    "preview_male",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="studio/preview/",
                    ),
                ),
                (
                    "preview_female",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="studio/preview/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("processing", "Обработка"),
                            ("review", "Ждёт проверки"),
                            ("failed", "Ошибка"),
                            ("published", "Опубликовано"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=16)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("keypoints", models.JSONField(blank=True, default=dict)),
                ("fit_score", models.FloatField(blank=True, null=True)),
                ("timings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="garment_jobs",
                        to="api.clothingcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garment_jobs",
                        to="api.telegramuser",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="garment_job",
                        to="api.clothingitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
